404 page
privacy-scaling-explorations/website-v2 pull request #85
Opened 2023-09-08 10:37 UTC by kalidiagne

**Desktop** 
<img width="600" alt="Screenshot 2023-09-08 at 11 33 55" src="https://github.com/privacy-scaling-explorations/website-v2/assets/20865711/bdba4ffd-8f87-4067-ab8f-7aca5bfbc106">

**Mobile**
<img width="300" alt="Screenshot 2023-09-08 at 11 34 02" src="https://github.com/privacy-scaling-explorations/website-v2/assets/20865711/8dfead27-e7fc-480e-a6de-bd7bd19bf963">

2023-09-08 10:39 UTC, kalidiagne commented
There from here 

https://website-v2-git-76-devel-fb72be-privacy-and-scaling-explorations.vercel.app/wwww 

@ChialiT @thebeyondr

2023-09-08 13:28 UTC, ChialiT approved these changes
I will approve as it is, but we need to swap the asset.
once asset is updated, I think we are good to go.

2023-09-08 13:28 UTC, ChialiT commented on public/icons/emotion-sad-line.svg
Design team suppose to supply a new asset for this.

2023-09-08 18:22 UTC, thebeyondr requested changes
new asset to replace the sad img

2023-09-11 11:06 UTC, kalidiagne commented
> new asset to replace the sad img

Asset replaced 👍

2023-09-14 18:26 UTC, thebeyondr approved these changes

2023-09-14 19:29 UTC, merged